travis:
  secure:
    BINSTAR_TOKEN: U394hJy1oMSAiZxx80G/oz0vkRWd0/I1qE4RmERuNcsXo6nQMh/iFRGKe+Zhc/k7lzb7sbJ3YnMuu99LwMPNonMFC2jSmxg0BhASU6dwqhs1+y5ebNFI1MZ+YjizICuFndoKXDZSWq90ZLh3GD4KiE1sNChmlcM8ooUG8bH211TVpaoQLTJCr51diys6QKNwKA8McE8vRGZz8QXdgz5bmw/8wpO6/M3liHz/bxjNL2O2SguqZFmii2OiVruqxo1+1ylUrLOcnvL+Xd0CYKEIt/nWHJHvGNd5k/qZKCnbX0dxvDWMr5hSacJlC0mTEgSi/tlXrOcL0tgXUR5j/AcpXVtHNTx8SLFDKqqhKCpvktn901f8vMX4uJ68sM9RoXfHGKIQDTGfnGt0ffyLURfz6mnFtQbdPiLJgdypQt6uZUFp7LA+uUWzPTHLA7CpHvdT9aPzrMIviHh334eX77jAqBmyIV0anK83u4sK0yzdxrhhO/zb1Za6VYO/6U9z0Fhac0rYyi8PBwLCHikNP2Yvsm6MfHpX1VzIjJ35B0APE34NW6iGevhJlBE2Bzl0OlNzBIL00w/FhpjpbOGHA39quHDiNvHuoFysXiWcZhknaKC4RSWEggeZKMRJDng+TpZu/AQwbUclx1mIm7xBdjih9WO0TKJVy6GxVB7WyYWD6zw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
